version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "music-db"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=music
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
